POST http://localhost:8000/api/cinema
Content-Type: application/json

{
    "cineplexId":"61151435f51975506c621019",
    "movieId":"2",
    "cinema_name":"BHD Bình Thạnh",
    "address":"Quận bình thạnh",
    "logo":"1111"
}

###

POST http://localhost:8000/api/cineplex
Content-Type: application/json

{
    "cineplex_name":"BHDStar"
}


###
GET http://localhost:8000/api/cinema
